# Generated by scripts/cluster/make_manifest.py from benchmark/run_config.yaml — do not edit by hand;
# regenerate after changing the run config. Sourced by the sbatch templates.
COMMON_FLAGS="--n-folds 5 --gt-rates 0 --learning-timeout-seconds 600 --planning-timeout-seconds 60 --search-mode dfs --node-choosing-strategy model_patch_first --model-constraint-weight 0.0 --conflict-group-strategy largest --fluent-branch-mode single --algorithms cdps --resume --simulated-masking-strategy percentage --simulated-noising-strategy percentage --simulated-seed 42"
