(define (problem n_puzzle_2)
  (:domain strips-sliding-tile)
  (:objects x1 x2 y1 y2 t1 t2 t3)
  (:init
    (at t2 x1 x1)
    (at t3 x1 x2)
    (blank x2 x1)
    (at t1 x2 x2)
    (position x1) (position x2)
    (position y1) (position y2)
    (tile t1) (tile t2) (tile t3)
    (inc x1 x2) (dec x2 x1)
    (inc y1 y2) (dec y2 y1)
    (up t1)
    (up t2)
    (up t3)
    (down t1)
    (down t2)
    (down t3)
    (left t1)
    (left t2)
    (left t3)
    (right t1)
    (right t2)
    (right t3)
  )
  (:goal (and
    (at t1 x1 x1)
    (at t2 x1 x2)
    (at t3 x2 x1))))
